[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = [
  'npm install',
  'cd server && npm install',
  'cd client && npm install'
]

[phases.build]
cmds = [
  'cd client && npm run build',
  'mkdir -p server/public',
  'cp -r client/build/* server/public/ || true'
]

[start]
cmd = 'cd server && npm start'